name: Lint and Test

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository (use actions/checkout@v4)
      - name: Checkout code
        uses: actions/checkout@v4

      # Extract Node.js version from package.json
      - name: Get Node.js version
        id: node_version
        run: echo "NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $GITHUB_ENV

      # Set up Node.js using the extracted version (use actions/setup-node@v4)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint
      - name: Run lint
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm run test
